DROP TABLE IF EXISTS "USER_PERMISSION" CASCADE;
DROP TABLE IF EXISTS "UD_USER_DATA" CASCADE;
DROP TABLE IF EXISTS "ABSTRACT_PROPERTY" CASCADE;
DROP TABLE IF EXISTS "UD_COUNTER_PROPERTY" CASCADE;
DROP TABLE IF EXISTS "UD_PROPERTY" CASCADE;
DROP TABLE IF EXISTS "UD_ATTRIBUTE_TYPE" CASCADE;
DROP TABLE IF EXISTS "UD_OBJECT_TYPE_ATTRIBUTES" CASCADE;
DROP TABLE IF EXISTS "UD_ATTRIBUTE" CASCADE;
DROP TABLE IF EXISTS "UD_OBJECT_TYPE" CASCADE;
DROP TABLE IF EXISTS "UD_OBJECT" CASCADE;

CREATE TABLE "UD_ATTRIBUTE_TYPE"
(
	"ATTR_TYPE_ID" BIGINT PRIMARY KEY,
	"NAME" VARCHAR(50) NOT NULL,
	"ABBRIVIATION" VARCHAR(20) UNIQUE,
	"ATTR_PARAMS" VARCHAR(50),
	"ATTR_TYPE_HANDLER" VARCHAR(50) NOT NULL
);

CREATE TABLE "UD_ATTRIBUTE"
(
	"ATTR_ID" BIGINT PRIMARY KEY,
	"ATTR_TYPE_ID" BIGINT NOT NULL REFERENCES "UD_ATTRIBUTE_TYPE"("ATTR_TYPE_ID"),
	"ABBRIVIATION" VARCHAR(20) UNIQUE NOT NULL,
	"NAME" VARCHAR(50) NOT NULL,
	"ATTR_TAGS" VARCHAR(50),
	"ATTR_PARAMS" VARCHAR(50),
	"IS_SYSTEM" BOOLEAN NOT NULL
);

CREATE TABLE "UD_OBJECT_TYPE"
(
	"OBJECT_TYPE_ID" BIGINT PRIMARY KEY,
	"PARENT_TYPE_ID" BIGINT REFERENCES "UD_OBJECT_TYPE"("OBJECT_TYPE_ID"),
	"NAME" VARCHAR(50) NOT NULL,
	"ABBRIVIATION" VARCHAR(20) UNIQUE,
	"IS_SYSTEM" BOOLEAN NOT NULL
);

CREATE TABLE "UD_OBJECT_TYPE_ATTRIBUTES"
(
	"OBJECT_TYPE_ID" BIGINT REFERENCES "UD_OBJECT_TYPE"("OBJECT_TYPE_ID"),
    "ATTR_ID" BIGINT REFERENCES "UD_ATTRIBUTE"("ATTR_ID"),
	PRIMARY KEY("OBJECT_TYPE_ID","ATTR_ID")
);

CREATE TABLE "UD_OBJECT"
(
	"OBJECT_ID" BIGINT PRIMARY KEY,
	"OBJECT_TYPE_ID" BIGINT NOT NULL REFERENCES "UD_OBJECT_TYPE"("OBJECT_TYPE_ID"),
	"PARENT_OBJECT_ID" BIGINT REFERENCES "UD_OBJECT"("OBJECT_ID"),
	"NAME" VARCHAR(50) NOT NULL,
	"ABBRIVIATION" VARCHAR(20),
	"SECURITY_LEVEL" INTEGER,
	"OWNER_USER_ID" BIGINT
);

CREATE TABLE "UD_USER_DATA"
(
	"USER_ID" BIGINT PRIMARY KEY,
	"USER_ABBRIVIATION" VARCHAR(50) UNIQUE NOT NULL,
	"USER_LOGIN" VARCHAR(50) UNIQUE NOT NULL,
	"USER_PASSWORD" VARCHAR(50) NOT NULL,
	"USER_OBJECT_ID" BIGINT REFERENCES "UD_OBJECT"("OBJECT_ID"),
	"USER_CATEGORY" INTEGER NOT NULL
);

ALTER TABLE "UD_OBJECT" ADD CONSTRAINT "UD_OBJECT_OWNER_USER_ID_fkey" FOREIGN KEY ("OWNER_USER_ID") REFERENCES "UD_USER_DATA" ("USER_ID") MATCH FULL;

CREATE TABLE "USER_PERMISSION"
(
	"OBJECT_ID" BIGINT REFERENCES "UD_OBJECT"("OBJECT_ID"),
	"USER_ID" BIGINT REFERENCES "UD_USER_DATA"("USER_ID"),
	"OWNER_FLAG" BOOLEAN,
	"ACCESS_FLAG" BOOLEAN,
	PRIMARY KEY("OBJECT_ID","USER_ID")
);

CREATE TABLE "ABSTRACT_PROPERTY"
(
	"OBJECT_ID" BIGINT REFERENCES "UD_OBJECT"("OBJECT_ID"),
	"PROPERTY_ID" BIGINT,
	"ATTR_ID" BIGINT REFERENCES "UD_ATTRIBUTE"("ATTR_ID"),
	PRIMARY KEY("OBJECT_ID","PROPERTY_ID","ATTR_ID")
);

CREATE TABLE "UD_COUNTER_PROPERTY"
(
	"PROPERTY_ID" BIGINT,
	"ATTR_ID" BIGINT REFERENCES "UD_ATTRIBUTE"("ATTR_ID"),
	"DATE" TIMESTAMP,
	"VALUE_PROPERTY_ID" BIGINT NOT NULL,
	PRIMARY KEY("PROPERTY_ID","ATTR_ID","DATE")
);

CREATE TABLE "UD_PROPERTY"
(
	"PROPERTY_ID" BIGINT,
	"ATTR_ID" BIGINT REFERENCES "UD_ATTRIBUTE"("ATTR_ID"),
	"STRING_VALUE" VARCHAR(200),
	"REFERENCE_VALUE" BIGINT REFERENCES "UD_OBJECT"("OBJECT_ID"),
	"NUMERIC_VALUE" INTEGER,
	"BINARY_VALUE" BYTEA,
	"CHANGE_DATE" TIMESTAMP NOT NULL,
	"CREATE_DATE" TIMESTAMP NOT NULL,
	PRIMARY KEY("PROPERTY_ID","ATTR_ID")
);