--Здесь заполнить БД тестовыми данными
insert into UD_ATTRIBUTE_TYPE (NAME, ABBRIVIATION, ATTR_PARAMS, ATTR_TYPE_HANDLER) values ('String', 'str', '', 'string_handler')
insert into UD_ATTRIBUTE_TYPE (NAME, ABBRIVIATION, ATTR_PARAMS, ATTR_TYPE_HANDLER) values ('Number', 'int', '', 'integer_handler')
insert into UD_ATTRIBUTE (ATTR_TYPE_ID, ABBRIVIATION, NAME, IS_SYSTEM) values (1, 'name', 'Object name', true)
insert into UD_ATTRIBUTE (ATTR_TYPE_ID, ABBRIVIATION, NAME, IS_SYSTEM) values (2, 'number', 'Object value', true)
insert into UD_OBJECT_TYPE (PARENT_TYPE_ID, NAME, ABBRIVIATION, IS_SYSTEM) values (null, 'Blah Blah type', 'blah', false)
insert into UD_OBJECT_TYPE_ATTRIBUTES (OBJECT_TYPE_ID, ATTR_ID) values (1, 1)
insert into UD_OBJECT_TYPE_ATTRIBUTES (OBJECT_TYPE_ID, ATTR_ID) values (1, 2)
insert into UD_OBJECT (OBJECT_TYPE_ID, PARENT_OBJECT_ID, NAME, ABBRIVIATION) values (1, null, 'Blah Blah object', 'blah')
insert into UD_OBJECT (OBJECT_TYPE_ID, PARENT_OBJECT_ID, NAME, ABBRIVIATION) values (1, null, 'Foo object', 'foo')
insert into UD_USER_DATA (USER_ABBRIVIATION, USER_LOGIN, USER_PASSWORD, USER_OBJECT_ID, USER_CATEGORY) values ('vasya', 'Vasya_Pupkin', '12345', null, 1)
insert into UD_PROPERTY (ATTR_ID, STRING_VALUE, CHANGE_DATE, CREATE_DATE) values (1, 'Mega object', current_timestamp, current_timestamp)
insert into ABSTRACT_PROPERTY (OBJECT_ID, ATTR_ID, PROPERTY_ID) values (1, 1, 1)
insert into UD_PROPERTY (ATTR_ID, STRING_VALUE, CHANGE_DATE, CREATE_DATE) values (2, 'kakoeto chislo', current_timestamp, current_timestamp)
insert into ABSTRACT_PROPERTY (OBJECT_ID, ATTR_ID, PROPERTY_ID) values (2, 2, 2)
insert into UD_PROPERTY (ATTR_ID, STRING_VALUE, CHANGE_DATE, CREATE_DATE) values (1, 'Super object', current_timestamp, current_timestamp)
insert into ABSTRACT_PROPERTY (OBJECT_ID, ATTR_ID, PROPERTY_ID) values (2, 1, 3)