CREATE TABLE `UD_ATTRIBUTE_TYPE`
(
	`ATTR_TYPE_ID` INTEGER PRIMARY KEY,
	`NAME` TEXT NOT NULL,
	`ABBREVIATION` TEXT UNIQUE NOT NULL,
	`ATTR_PARAMS` TEXT,
	`ATTR_TYPE_HANDLER` TEXT NOT NULL
);

CREATE TABLE `UD_ATTRIBUTE`
(
	`ATTR_ID` INTEGER PRIMARY KEY,
	`ATTR_TYPE_ID` INTEGER NOT NULL REFERENCES `UD_ATTRIBUTE_TYPE`(`ATTR_TYPE_ID`),
	`ABBREVIATION` TEXT UNIQUE NOT NULL,
	`NAME` TEXT NOT NULL,
	`ATTR_TAGS` TEXT,
	`ATTR_PARAMS` TEXT,
	`IS_SYSTEM` INTEGER NOT NULL
);

CREATE TABLE `UD_OBJECT_TYPE`
(
	`OBJECT_TYPE_ID` INTEGER PRIMARY KEY,
	`PARENT_TYPE_ID` INTEGER REFERENCES `UD_OBJECT_TYPE`(`OBJECT_TYPE_ID`),
	`NAME` TEXT NOT NULL,
	`ABBREVIATION` TEXT UNIQUE,
	`IS_SYSTEM` INTEGER NOT NULL
);

CREATE TABLE `UD_OBJECT_TYPE_ATTRIBUTES`
(
	`OBJECT_TYPE_ID` INTEGER REFERENCES `UD_OBJECT_TYPE`(`OBJECT_TYPE_ID`),
    `ATTR_ID` INTEGER REFERENCES `UD_ATTRIBUTE`(`ATTR_ID`),
	PRIMARY KEY(`OBJECT_TYPE_ID`,`ATTR_ID`)
);

CREATE TABLE `UD_OBJECT`
(
	`OBJECT_ID` INTEGER PRIMARY KEY,
	`OBJECT_TYPE_ID` INTEGER NOT NULL REFERENCES `UD_OBJECT_TYPE`(`OBJECT_TYPE_ID`),
	`PARENT_OBJECT_ID` INTEGER REFERENCES `UD_OBJECT`(`OBJECT_ID`),
	`NAME` TEXT NOT NULL,
	`ABBREVIATION` TEXT,
	`SECURITY_LEVEL` INTEGER,
	`OWNER_USER_ID` INTEGER
);

CREATE TABLE `UD_USER_DATA`
(
	`USER_ID` INTEGER PRIMARY KEY,
	`USER_ABBREVIATION` TEXT UNIQUE NOT NULL,
	`USER_LOGIN` TEXT UNIQUE NOT NULL,
	`USER_PASSWORD` TEXT NOT NULL,
	`USER_OBJECT_ID` INTEGER REFERENCES `UD_OBJECT`(`OBJECT_ID`),
	`USER_CATEGORY` INTEGER NOT NULL
);


CREATE TABLE `UD_USER_PERMISSION`
(
	`OBJECT_ID` INTEGER REFERENCES `UD_OBJECT`(`OBJECT_ID`),
	`USER_ID` INTEGER REFERENCES `UD_USER_DATA`(`USER_ID`),
	`OWNER_FLAG` INTEGER,
	`ACCESS_FLAG` INTEGER,
	PRIMARY KEY(`OBJECT_ID`,`USER_ID`)
);

CREATE TABLE `UD_ABSTRACT_PROPERTY`
(
	`OBJECT_ID` INTEGER REFERENCES `UD_OBJECT`(`OBJECT_ID`),
	`PROPERTY_ID` INTEGER,
	`ATTR_ID` INTEGER REFERENCES `UD_ATTRIBUTE`(`ATTR_ID`),
	PRIMARY KEY(`OBJECT_ID`,`PROPERTY_ID`,`ATTR_ID`)
);

CREATE TABLE `UD_COUNTER_PROPERTY`
(
	`PROPERTY_ID` INTEGER,
	`ATTR_ID` INTEGER REFERENCES `UD_ATTRIBUTE`(`ATTR_ID`),
	`DATE` TEXT,
	`VALUE_PROPERTY_ID` INTEGER NOT NULL,
	PRIMARY KEY(`PROPERTY_ID`,`ATTR_ID`,`DATE`)
);

CREATE TABLE `UD_PROPERTY`
(
	`PROPERTY_ID` INTEGER,
	`ATTR_ID` INTEGER REFERENCES `UD_ATTRIBUTE`(`ATTR_ID`),
	`STRING_VALUE` TEXT,
	`REFERENCE_VALUE` INTEGER REFERENCES `UD_OBJECT`(`OBJECT_ID`),
	`NUMERIC_VALUE` INTEGER,
	`BINARY_VALUE` BLOB,
	`CHANGE_DATE` TEXT NOT NULL,
	`CREATE_DATE` TEXT NOT NULL,
	PRIMARY KEY(`PROPERTY_ID`,`ATTR_ID`)
);